# Copyright (C) 2015-2016 The CyanogenMod Project
# Copyright (C) 2017-2018 The LineageOS Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/msft/cityman/setup-makefiles.sh

# Set the local path to the current directory for the build system
LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),cityman)

# Clear all local variables (LOCAL_*) before starting a new module definition
include $(CLEAR_VARS)
# Define the name of the module being built
LOCAL_MODULE := HiddenMenu
# Define the name of the module being built
LOCAL_MODULE_OWNER := lge
# Specify the source files used to build this module
LOCAL_SRC_FILES := proprietary/app/HiddenMenu/HiddenMenu.apk
# Configure LOCAL_CERTIFICATE setting
LOCAL_CERTIFICATE := platform
# Define the name of the module being built
LOCAL_MODULE_TAGS := optional
# Define the name of the module being built
LOCAL_MODULE_CLASS := APPS
# Configure LOCAL_DEX_PREOPT setting
LOCAL_DEX_PREOPT := false
# Define the name of the module being built
LOCAL_MODULE_SUFFIX := .apk
# Instruct the build system to copy a prebuilt file
LOCAL_OPTIONAL_USES_LIBRARIES := com.qualcomm.qcrilhook
include $(BUILD_PREBUILT)

# Clear all local variables (LOCAL_*) before starting a new module definition
include $(CLEAR_VARS)
# Define the name of the module being built
LOCAL_MODULE := RCSBootstraputil
# Define the name of the module being built
LOCAL_MODULE_OWNER := lge
# Specify the source files used to build this module
LOCAL_SRC_FILES := proprietary/app/RCSBootstraputil/RCSBootstraputil.apk
# Configure LOCAL_CERTIFICATE setting
LOCAL_CERTIFICATE := platform
# Define the name of the module being built
LOCAL_MODULE_TAGS := optional
# Define the name of the module being built
LOCAL_MODULE_CLASS := APPS
# Configure LOCAL_DEX_PREOPT setting
LOCAL_DEX_PREOPT := false
# Define the name of the module being built
LOCAL_MODULE_SUFFIX := .apk
# Instruct the build system to copy a prebuilt file
include $(BUILD_PREBUILT)

# Clear all local variables (LOCAL_*) before starting a new module definition
include $(CLEAR_VARS)
# Define the name of the module being built
LOCAL_MODULE := RcsImsBootstraputil
# Define the name of the module being built
LOCAL_MODULE_OWNER := lge
# Specify the source files used to build this module
LOCAL_SRC_FILES := proprietary/app/RcsImsBootstraputil/RcsImsBootstraputil.apk
# Configure LOCAL_CERTIFICATE setting
LOCAL_CERTIFICATE := platform
# Define the name of the module being built
LOCAL_MODULE_TAGS := optional
# Define the name of the module being built
LOCAL_MODULE_CLASS := APPS
# Configure LOCAL_DEX_PREOPT setting
LOCAL_DEX_PREOPT := false
# Define the name of the module being built
LOCAL_MODULE_SUFFIX := .apk
# Instruct the build system to copy a prebuilt file
include $(BUILD_PREBUILT)

# Clear all local variables (LOCAL_*) before starting a new module definition
include $(CLEAR_VARS)
# Define the name of the module being built
LOCAL_MODULE := CNEService
# Define the name of the module being built
LOCAL_MODULE_OWNER := lge
# Specify the source files used to build this module
LOCAL_SRC_FILES := proprietary/priv-app/CNEService/CNEService.apk
# Configure LOCAL_CERTIFICATE setting
LOCAL_CERTIFICATE := platform
# Define the name of the module being built
LOCAL_MODULE_TAGS := optional
# Define the name of the module being built
LOCAL_MODULE_CLASS := APPS
# Configure LOCAL_DEX_PREOPT setting
LOCAL_DEX_PREOPT := false
# Define the name of the module being built
LOCAL_MODULE_SUFFIX := .apk
# Configure LOCAL_PRIVILEGED_MODULE setting
LOCAL_PRIVILEGED_MODULE := true
# Instruct the build system to copy a prebuilt file
include $(BUILD_PREBUILT)

# Clear all local variables (LOCAL_*) before starting a new module definition
include $(CLEAR_VARS)
# Define the name of the module being built
LOCAL_MODULE := DCMO
# Define the name of the module being built
LOCAL_MODULE_OWNER := lge
# Specify the source files used to build this module
LOCAL_SRC_FILES := proprietary/priv-app/DCMO/DCMO.apk
# Configure LOCAL_CERTIFICATE setting
LOCAL_CERTIFICATE := platform
# Define the name of the module being built
LOCAL_MODULE_TAGS := optional
# Define the name of the module being built
LOCAL_MODULE_CLASS := APPS
# Configure LOCAL_DEX_PREOPT setting
LOCAL_DEX_PREOPT := false
# Define the name of the module being built
LOCAL_MODULE_SUFFIX := .apk
# Configure LOCAL_PRIVILEGED_MODULE setting
LOCAL_PRIVILEGED_MODULE := true
# Instruct the build system to copy a prebuilt file
LOCAL_OPTIONAL_USES_LIBRARIES := com.qualcomm.qcrilhook
include $(BUILD_PREBUILT)

# Clear all local variables (LOCAL_*) before starting a new module definition
include $(CLEAR_VARS)
# Define the name of the module being built
LOCAL_MODULE := DMConfigUpdate
# Define the name of the module being built
LOCAL_MODULE_OWNER := lge
# Specify the source files used to build this module
LOCAL_SRC_FILES := proprietary/priv-app/DMConfigUpdate/DMConfigUpdate.apk
# Configure LOCAL_CERTIFICATE setting
LOCAL_CERTIFICATE := platform
# Define the name of the module being built
LOCAL_MODULE_TAGS := optional
# Define the name of the module being built
LOCAL_MODULE_CLASS := APPS
# Configure LOCAL_DEX_PREOPT setting
LOCAL_DEX_PREOPT := false
# Define the name of the module being built
LOCAL_MODULE_SUFFIX := .apk
# Configure LOCAL_PRIVILEGED_MODULE setting
LOCAL_PRIVILEGED_MODULE := true
# Instruct the build system to copy a prebuilt file
LOCAL_OPTIONAL_USES_LIBRARIES := com.qualcomm.qcrilhook
include $(BUILD_PREBUILT)

# Clear all local variables (LOCAL_*) before starting a new module definition
include $(CLEAR_VARS)
# Define the name of the module being built
LOCAL_MODULE := DiagMon
# Define the name of the module being built
LOCAL_MODULE_OWNER := lge
# Specify the source files used to build this module
LOCAL_SRC_FILES := proprietary/priv-app/DiagMon/DiagMon.apk
# Configure LOCAL_CERTIFICATE setting
LOCAL_CERTIFICATE := platform
# Define the name of the module being built
LOCAL_MODULE_TAGS := optional
# Define the name of the module being built
LOCAL_MODULE_CLASS := APPS
# Configure LOCAL_DEX_PREOPT setting
LOCAL_DEX_PREOPT := false
# Define the name of the module being built
LOCAL_MODULE_SUFFIX := .apk
# Configure LOCAL_PRIVILEGED_MODULE setting
LOCAL_PRIVILEGED_MODULE := true
# Instruct the build system to copy a prebuilt file
include $(BUILD_PREBUILT)

# Clear all local variables (LOCAL_*) before starting a new module definition
include $(CLEAR_VARS)
# Define the name of the module being built
LOCAL_MODULE := HotwordEnrollmentOKGoogleWCD9330
# Define the name of the module being built
LOCAL_MODULE_OWNER := lge
# Specify the source files used to build this module
LOCAL_SRC_FILES := proprietary/priv-app/HotwordEnrollmentOKGoogleWCD9330/HotwordEnrollmentOKGoogleWCD9330.apk
# Configure LOCAL_CERTIFICATE setting
LOCAL_CERTIFICATE := PRESIGNED
# Define the name of the module being built
LOCAL_MODULE_TAGS := optional
# Define the name of the module being built
LOCAL_MODULE_CLASS := APPS
# Configure LOCAL_DEX_PREOPT setting
LOCAL_DEX_PREOPT := false
# Define the name of the module being built
LOCAL_MODULE_SUFFIX := .apk
# Configure LOCAL_PRIVILEGED_MODULE setting
LOCAL_PRIVILEGED_MODULE := true
# Instruct the build system to copy a prebuilt file
include $(BUILD_PREBUILT)

# Clear all local variables (LOCAL_*) before starting a new module definition
include $(CLEAR_VARS)
# Define the name of the module being built
LOCAL_MODULE := HotwordEnrollmentTGoogleWCD9330
# Define the name of the module being built
LOCAL_MODULE_OWNER := lge
# Specify the source files used to build this module
LOCAL_SRC_FILES := proprietary/priv-app/HotwordEnrollmentTGoogleWCD9330/HotwordEnrollmentTGoogleWCD9330.apk
# Configure LOCAL_CERTIFICATE setting
LOCAL_CERTIFICATE := PRESIGNED
# Define the name of the module being built
LOCAL_MODULE_TAGS := optional
# Define the name of the module being built
LOCAL_MODULE_CLASS := APPS
# Configure LOCAL_DEX_PREOPT setting
LOCAL_DEX_PREOPT := false
# Define the name of the module being built
LOCAL_MODULE_SUFFIX := .apk
# Configure LOCAL_PRIVILEGED_MODULE setting
LOCAL_PRIVILEGED_MODULE := true
# Instruct the build system to copy a prebuilt file
include $(BUILD_PREBUILT)

# Clear all local variables (LOCAL_*) before starting a new module definition
include $(CLEAR_VARS)
# Define the name of the module being built
LOCAL_MODULE := HotwordEnrollmentXGoogleWCD9330
# Define the name of the module being built
LOCAL_MODULE_OWNER := lge
# Specify the source files used to build this module
LOCAL_SRC_FILES := proprietary/priv-app/HotwordEnrollmentXGoogleWCD9330/HotwordEnrollmentXGoogleWCD9330.apk
# Configure LOCAL_CERTIFICATE setting
LOCAL_CERTIFICATE := PRESIGNED
# Define the name of the module being built
LOCAL_MODULE_TAGS := optional
# Define the name of the module being built
LOCAL_MODULE_CLASS := APPS
# Configure LOCAL_DEX_PREOPT setting
LOCAL_DEX_PREOPT := false
# Define the name of the module being built
LOCAL_MODULE_SUFFIX := .apk
# Configure LOCAL_PRIVILEGED_MODULE setting
LOCAL_PRIVILEGED_MODULE := true
# Instruct the build system to copy a prebuilt file
include $(BUILD_PREBUILT)

# Clear all local variables (LOCAL_*) before starting a new module definition
include $(CLEAR_VARS)
# Define the name of the module being built
LOCAL_MODULE := LifeTimerService
# Define the name of the module being built
LOCAL_MODULE_OWNER := lge
# Specify the source files used to build this module
LOCAL_SRC_FILES := proprietary/priv-app/LifeTimerService/LifeTimerService.apk
# Configure LOCAL_CERTIFICATE setting
LOCAL_CERTIFICATE := platform
# Define the name of the module being built
LOCAL_MODULE_TAGS := optional
# Define the name of the module being built
LOCAL_MODULE_CLASS := APPS
# Configure LOCAL_DEX_PREOPT setting
LOCAL_DEX_PREOPT := false
# Define the name of the module being built
LOCAL_MODULE_SUFFIX := .apk
# Configure LOCAL_PRIVILEGED_MODULE setting
LOCAL_PRIVILEGED_MODULE := true
# Instruct the build system to copy a prebuilt file
LOCAL_USES_LIBRARIES := com.qualcomm.qcrilhook
include $(BUILD_PREBUILT)

# Clear all local variables (LOCAL_*) before starting a new module definition
include $(CLEAR_VARS)
# Define the name of the module being built
LOCAL_MODULE := atfwd
# Define the name of the module being built
LOCAL_MODULE_OWNER := lge
# Specify the source files used to build this module
LOCAL_SRC_FILES := proprietary/priv-app/atfwd/atfwd.apk
# Configure LOCAL_CERTIFICATE setting
LOCAL_CERTIFICATE := platform
# Define the name of the module being built
LOCAL_MODULE_TAGS := optional
# Define the name of the module being built
LOCAL_MODULE_CLASS := APPS
# Configure LOCAL_DEX_PREOPT setting
LOCAL_DEX_PREOPT := false
# Define the name of the module being built
LOCAL_MODULE_SUFFIX := .apk
# Configure LOCAL_PRIVILEGED_MODULE setting
LOCAL_PRIVILEGED_MODULE := true
# Instruct the build system to copy a prebuilt file
include $(BUILD_PREBUILT)

# Clear all local variables (LOCAL_*) before starting a new module definition
include $(CLEAR_VARS)
# Define the name of the module being built
LOCAL_MODULE := qcrilmsgtunnel
# Define the name of the module being built
LOCAL_MODULE_OWNER := lge
# Specify the source files used to build this module
LOCAL_SRC_FILES := proprietary/priv-app/qcrilmsgtunnel/qcrilmsgtunnel.apk
# Configure LOCAL_CERTIFICATE setting
LOCAL_CERTIFICATE := platform
# Define the name of the module being built
LOCAL_MODULE_TAGS := optional
# Define the name of the module being built
LOCAL_MODULE_CLASS := APPS
# Configure LOCAL_DEX_PREOPT setting
LOCAL_DEX_PREOPT := false
# Define the name of the module being built
LOCAL_MODULE_SUFFIX := .apk
# Configure LOCAL_PRIVILEGED_MODULE setting
LOCAL_PRIVILEGED_MODULE := true
LOCAL_OPTIONAL_USES_LIBRARIES := android.hidl.base-V1.0-java android.hidl.manager-V1.0-java
# Instruct the build system to copy a prebuilt file
LOCAL_USES_LIBRARIES := android.hidl.manager@1.0-java
include $(BUILD_PREBUILT)

# Clear all local variables (LOCAL_*) before starting a new module definition
include $(CLEAR_VARS)
# Define the name of the module being built
LOCAL_MODULE := cneapiclient
# Define the name of the module being built
LOCAL_MODULE_OWNER := lge
# Specify the source files used to build this module
LOCAL_SRC_FILES := proprietary/framework/cneapiclient.jar
# Configure LOCAL_CERTIFICATE setting
LOCAL_CERTIFICATE := PRESIGNED
# Define the name of the module being built
LOCAL_MODULE_TAGS := optional
# Define the name of the module being built
LOCAL_MODULE_CLASS := JAVA_LIBRARIES
# Define the name of the module being built
LOCAL_MODULE_SUFFIX := .jar
# Instruct the build system to copy a prebuilt file
include $(BUILD_PREBUILT)

# Clear all local variables (LOCAL_*) before starting a new module definition
include $(CLEAR_VARS)
# Define the name of the module being built
LOCAL_MODULE := com.google.android.camera.experimental2016
# Define the name of the module being built
LOCAL_MODULE_OWNER := lge
# Specify the source files used to build this module
LOCAL_SRC_FILES := proprietary/framework/com.google.android.camera.experimental2016.jar
# Configure LOCAL_CERTIFICATE setting
LOCAL_CERTIFICATE := PRESIGNED
# Define the name of the module being built
LOCAL_MODULE_TAGS := optional
# Define the name of the module being built
LOCAL_MODULE_CLASS := JAVA_LIBRARIES
# Define the name of the module being built
LOCAL_MODULE_SUFFIX := .jar
# Instruct the build system to copy a prebuilt file
include $(BUILD_PREBUILT)

# Clear all local variables (LOCAL_*) before starting a new module definition
include $(CLEAR_VARS)
# Define the name of the module being built
LOCAL_MODULE := qcrilhook
# Define the name of the module being built
LOCAL_MODULE_OWNER := lge
# Specify the source files used to build this module
LOCAL_SRC_FILES := proprietary/framework/qcrilhook.jar
# Configure LOCAL_CERTIFICATE setting
LOCAL_CERTIFICATE := PRESIGNED
# Define the name of the module being built
LOCAL_MODULE_TAGS := optional
# Define the name of the module being built
LOCAL_MODULE_CLASS := JAVA_LIBRARIES
# Define the name of the module being built
LOCAL_MODULE_SUFFIX := .jar
# Instruct the build system to copy a prebuilt file
include $(BUILD_PREBUILT)

# Clear all local variables (LOCAL_*) before starting a new module definition
include $(CLEAR_VARS)
# Define the name of the module being built
LOCAL_MODULE := rcsimssettings
# Define the name of the module being built
LOCAL_MODULE_OWNER := lge
# Specify the source files used to build this module
LOCAL_SRC_FILES := proprietary/framework/rcsimssettings.jar
# Configure LOCAL_CERTIFICATE setting
LOCAL_CERTIFICATE := PRESIGNED
# Define the name of the module being built
LOCAL_MODULE_TAGS := optional
# Define the name of the module being built
LOCAL_MODULE_CLASS := JAVA_LIBRARIES
# Define the name of the module being built
LOCAL_MODULE_SUFFIX := .jar
# Instruct the build system to copy a prebuilt file
include $(BUILD_PREBUILT)

# Clear all local variables (LOCAL_*) before starting a new module definition
include $(CLEAR_VARS)
# Define the name of the module being built
LOCAL_MODULE := rcsservice
# Define the name of the module being built
LOCAL_MODULE_OWNER := lge
# Specify the source files used to build this module
LOCAL_SRC_FILES := proprietary/framework/rcsservice.jar
# Configure LOCAL_CERTIFICATE setting
LOCAL_CERTIFICATE := PRESIGNED
# Define the name of the module being built
LOCAL_MODULE_TAGS := optional
# Define the name of the module being built
LOCAL_MODULE_CLASS := JAVA_LIBRARIES
# Define the name of the module being built
LOCAL_MODULE_SUFFIX := .jar
# Instruct the build system to copy a prebuilt file
include $(BUILD_PREBUILT)

# Clear all local variables (LOCAL_*) before starting a new module definition
include $(CLEAR_VARS)
# Define the name of the module being built
LOCAL_MODULE := libtime_genoff
# Define the name of the module being built
LOCAL_MODULE_OWNER := lge
# Specify the source files used to build this module
LOCAL_SRC_FILES_64 := proprietary/vendor/lib64/libtime_genoff.so
# Specify the source files used to build this module
LOCAL_SRC_FILES_32 := proprietary/vendor/lib/libtime_genoff.so
# Configure LOCAL_MULTILIB setting
LOCAL_MULTILIB := both
# Define the name of the module being built
LOCAL_MODULE_TAGS := optional
# Define the name of the module being built
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
# Define the name of the module being built
LOCAL_MODULE_SUFFIX := .so
# Configure LOCAL_VENDOR_MODULE setting
LOCAL_VENDOR_MODULE := true
# List the shared libraries this module links against
LOCAL_SHARED_LIBRARIES := libc++ libc libcutils libdl liblog libm
# Instruct the build system to copy a prebuilt file
include $(BUILD_PREBUILT)

# Clear all local variables (LOCAL_*) before starting a new module definition
include $(CLEAR_VARS)
# Define the name of the module being built
LOCAL_MODULE := datastatusnotification
# Define the name of the module being built
LOCAL_MODULE_OWNER := lge
# Specify the source files used to build this module
LOCAL_SRC_FILES := proprietary/vendor/app/datastatusnotification/datastatusnotification.apk
# Configure LOCAL_CERTIFICATE setting
LOCAL_CERTIFICATE := platform
# Define the name of the module being built
LOCAL_MODULE_TAGS := optional
# Define the name of the module being built
LOCAL_MODULE_CLASS := APPS
# Configure LOCAL_DEX_PREOPT setting
LOCAL_DEX_PREOPT := false
# Define the name of the module being built
LOCAL_MODULE_SUFFIX := .apk
# Configure LOCAL_VENDOR_MODULE setting
LOCAL_VENDOR_MODULE := true
# Instruct the build system to copy a prebuilt file
LOCAL_USES_LIBRARIES := com.qualcomm.qcrilhook
include $(BUILD_PREBUILT)

#include $(CLEAR_VARS)
#LOCAL_MODULE := ims
#LOCAL_MODULE_OWNER := lge
#LOCAL_SRC_FILES := proprietary/vendor/app/ims/ims.apk
#LOCAL_CERTIFICATE := platform
#LOCAL_MODULE_TAGS := optional
#LOCAL_MODULE_CLASS := APPS
#LOCAL_DEX_PREOPT := false
#LOCAL_MODULE_SUFFIX := .apk
#LOCAL_VENDOR_MODULE := true
##include $(BUILD_PREBUILT)

endif
